package:
  name: {{ environ.get('RECIPE', 'torch2rt') | lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_rev: v0.4.0
  git_url: https://github.com/NVIDIA-AI-IOT/torch2trt

build:
  number: 0
  script_env:
  script: pip install -vv --no-deps --ignore-installed --no-build-isolation --no-binary ':all:' .

requirements:
  build:
    - {{ compiler('cxx') }}
    #- nvcc_linux-64 # [linux]
  host:
    - python={{ PY_VER }}
    - pytorch::pytorch={{ PTH_VER }}=*{{ PTH_BUILD }}*
    - tensorrt={{ TRT_VER }}
    - packaging
  run:
    - numpy
    - python={{ PY_VER }}
    - pytorch::pytorch={{ PTH_VER }}=*{{ PTH_BUILD }}*
    - pytorch::torchvision={{ PTV_VER }}
    - tensorrt={{ TRT_VER }}
test:
  imports:
    - torch2trt
    - torch2trt.torch2trt
  commands:

about:
  home: https://github.com/NVIDIA-AI-IOT/torch2trt
  license: Proprietary
  license_family: Proprietary
  summary: PyTorch module adapter for TensorRT