package:
  name: {{ environ.get('RECIPE', 'dcn-rfcn') | lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_rev: {{ GIT_DESCRIBE_TAG }}
  git_url: https://github.com/necla-ml/Deformable-ConvNets-py3

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  features:
{{ environ.get('CONDA_CPUONLY_FEATURE') }}
  script_env:
    - CONDA_CPUONLY_FEATURE

requirements:
  host:
    - cython
    - numpy
    - pip
    - python=3.7
  run:
    - easydict
    - numpy
    - opencv
    - python=3.7
    - pyyaml
    - requests
{{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}
{{ environ.get('NCCL_PACKAGE', '') }}
test:
  script_env:
    - CONDA_CPUONLY_FEATURE
  imports:
    - dcn.bbox.cpu
    - dcn.nms.cpu
    - dcn.nms.cuda
    - rfcn
  commands:
    {% if environ.get('CONDA_CPUONLY_FEATURE', '') == '' %}
    - $PYTHON -c 'import mxnet as mx; a = mx.nd.ones((2, 3), mx.gpu())'
    {% else %}
    - $PYTHON -c 'import mxnet as mx; a = mx.nd.ones((2, 3))'
    {% endif %}

about:
  home: https://github.com/necla-ml/Deformable-ConvNets-py3
  license: Apache License
  license_family: APACHE
  summary: Composable command line interface toolkit