package:
  name: {{ environ.get('RECIPE', 'eigen') | lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_rev: v0.0.1
  git_url: https://github.com/necla-ml/Eigen.git

build:
  number: 0
  script_env:
    - PY_VER
  string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_{{ environ.get('PKG_BUILDNUM') }}
  script: pip install -vv --no-deps --ignore-installed --no-build-isolation --no-binary ':all:' .
  features:
{{ environ.get('CONDA_CPUONLY_FEATURE', '') }}

requirements:
  build:
  host:
    - ml>=1.4.6
  run:
    - ml>=1.4.6
    - conda-forge::redis-py>=4.0.2 

test:
  imports:
    - eigen.rt
    - eigen.broker.redis

about:
  home: https://github.com/necla-ml/Eigen
  summary: A utility library to construct complex video analytics pipelines.
