{% set name = "gst-libav" %}
{% set version = "1.21.3" %}
{% set version_major_minor = ".".join(version.split(".")[:2]) %}
{% set posix = 'm2-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-{{ version }}.tar.xz
  sha256: e529646d020054244bf90e5903ffafd6231843d6037d97cce9e23207e6f45fd9

build:
  number: 0
  skip: true  # [osx]
  run_exports:
    # remove symbols at .90 patch releases just before minor versions?
    #    https://abi-laboratory.pro/tracker/timeline/gstreamer/
    - {{ pin_subpackage('gst-libav', max_pin='x.x') }}

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - meson
    - ninja
    - pkg-config
    - {{ posix }}patch  # [win]
  host:
    - conda-forge::ffmpeg=4.4.2=*lgpl*
    - gstreamer         {{ version_major_minor }}
    - gst-plugins-base  {{ version_major_minor }}
    - glib
    # Needed for gstreamer-audio-1.0 dependency?
    # Not sure why, zlib should be a private dependency
    - zlib

test:
  commands:
    - test -f ${PREFIX}/lib/gstreamer-1.0/libgstlibav${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstlibav.dll exit 1  # [win]
    - gst-inspect-1.0 --plugin libav

about:
  home: http://gstreamer.freedesktop.org/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: GStreamer plugin for the FFmpeg libav* libraries
  doc_url: https://gstreamer.freedesktop.org/modules/gst-libav.html
  dev_url: https://gitlab.freedesktop.org/gstreamer/gst-libav