{% set version = "0.7.7" %}

package:
  name: ml-vision
  version: {{ version }}

source:
  git_rev: v{{ version }}
  git_url: https://gitlab.com/necla-ml/ML-Vision.git

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  script: TORCH_CUDA_ARCH_LIST='5.3;7.2' pip install -vv --no-deps --ignore-installed --no-build-isolation --no-binary ':all:' .

requirements:
  build:
#    - gcc_linux-64  # [linux]
#    - gxx_linux-64  # [linux]
  host:
    - ml =0.11.1

  run:
    - ml =0.11.1
    - pycocotools >=2
    - torchvision

test:
  imports:
    - ml.av
    - ml.cv
    - ml.vision.ops
  commands:
    - $PYTHON -c 'import torch; import ml._C'

about:
  home: https://gitlab.com/necla-ml/ML-Vision
  license: BSD
  license_family: BSD
  summary: Composable command line interface toolkit
