package:
  name: {{ RECIPE }}
  version: 1.3.3

build:
  number: 0
  string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_0
  features:
{{ environ.get('CONDA_CPUONLY_FEATURE') }}
  script_env:
    - CONDA_CPUONLY_FEATURE
    - CUDA_PT_VER
    - PTH_VER

requirements:
  host:
    - cython
    - numpy
    - python=3.7
  run:
    - addict
    - json_tricks
    - matplotlib
    - munkres
    - opencv
    - python=3.7
    - pytorch={{ PTH_VER }}
    - pyyaml
    - regex           # [win]
    - scipy
    - tensorboard
    - torchvision
    - yapf
{{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}
test:
#  requires:
#    - pytest
  imports:
    - mmcv
    - mmcv.arraymisc
    - mmcv.cnn
    - mmcv.cnn.bricks
    - mmcv.fileio
    - mmcv.fileio.handlers
    - mmcv.image
    - mmcv.parallel
    - mmcv.runner
    - mmcv.runner.hooks
    - mmcv.runner.hooks.logger
    - mmcv.runner.optimizer
    - mmcv.utils
    - mmcv.video
    - mmcv.visualization

about:
  home: https://github.com/open-mmlab/mmcv
  license: Apache License 2.0
  license_family: APACHE
  summary: OpenMMLab Computer Vision Foundation