package:
  name: {{ RECIPE }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_rev: {{ GIT_DESCRIBE_TAG }}
  git_rev: v1.0.5
  git_url: https://github.com/open-mmlab/mmcv.git

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  features:
{{ environ.get('CONDA_CPUONLY_FEATURE') }}
  script_env:
    - CONDA_CPUONLY_FEATURE

requirements:
  host:
    - cython
    - numpy
    - python=3.7
#    - pytorch=1.6
  run:
    - addict
    - opencv
    - python=3.7
    - pytorch=1.6
    - pyyaml
    - regex           # [win]
    - torchvision
    - yapf
{{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}
test:
#  requires:
#    - pytest
  imports:
    - mmcv
    - mmcv.arraymisc
    - mmcv.cnn
    - mmcv.cnn.bricks
    - mmcv.fileio
    - mmcv.fileio.handlers
    - mmcv.image
    - mmcv.parallel
    - mmcv.runner
    - mmcv.runner.hooks
    - mmcv.runner.hooks.logger
    - mmcv.runner.optimizer
    - mmcv.utils
    - mmcv.video
    - mmcv.video.optflow_warp
    - mmcv.visualization

about:
  home: https://github.com/open-mmlab/mmcv
  license: Apache License 2.0
  license_family: APACHE
  summary: OpenMMLab Computer Vision Foundation