package:
  name: {{ environ.get('RECIPE', 'mmcv') | lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_rev: {{ GIT_DESCRIBE_TAG }}
  git_rev: be945648c4a9f01fc519814b1b0e8b4ada77c8b7
  git_rev: v1.3.14
  git_url: https://github.com/open-mmlab/mmcv.git

build:
  number: 0
  script_env:
    - PY_VER
    - PTH_VER
    - PTV_VER
    - CUDA_PT_VER
    - TORCH_CUDA_ARCH_LIST
  string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_0
  features:
{{ environ.get('CONDA_CPUONLY_FEATURE') }}
  script: MMCV_WITH_OPS=1 pip install .
  # script: MMCV_WITH_OPS=1 pip install -vv --no-deps --ignore-installed --no-build-isolation .

requirements:
  host:
    - cython
    - numpy
    - pip
    - pytest-runner
    - python={{ PY_VER }}
    - pytorch::pytorch={{ PTH_VER }}
    
  run:
    - addict
    - json_tricks
    - matplotlib
    - munkres
    - opencv-python
    - packaging
    - python={{ PY_VER }}
    - pytorch::pytorch={{ PTH_VER }}
    - pyyaml
    - regex           # [win]
    - scipy
    - tensorboard
    - pytorch::torchvision={{ PTV_VER }}
    - yapf
{{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}
test:
#  requires:
#    - pytest
  imports:
    - mmcv
    - mmcv.arraymisc
    - mmcv.cnn
    - mmcv.cnn.bricks
    - mmcv.fileio
    - mmcv.fileio.handlers
    - mmcv.image
    - mmcv.parallel
    - mmcv.runner
    - mmcv.runner.hooks
    - mmcv.runner.hooks.logger
    - mmcv.runner.optimizer
    - mmcv.utils
    - mmcv.video
    - mmcv.visualization

about:
  home: https://github.com/open-mmlab/mmcv
  license: Apache License 2.0
  license_family: APACHE
  summary: OpenMMLab Computer Vision Foundation