package:
  name: {{ environ.get('RECIPE', 'mmpose') | lower }}
  version: 0.19.0

build:
  number: 0
  string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_0
  features:
{{ environ.get('CONDA_CPUONLY_FEATURE') }}
  script_env:
    - CONDA_CPUONLY_FEATURE
    - CUDA_PT_VER
    - PTH_VER

requirements:
  host:
    - numpy
    - pip
    - python={{ PY_VER }}
  run:
    - mmcv=1.3.14
    - python={{ PY_VER }}
    - shapely
{{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}
test:
#  requires:
#    - pytest
  imports:
    - mmpose

about:
  home: https://github.com/open-mmlab/mmpose
  license: Apache License 2.0
  license_family: APACHE
  summary: OpenMMLab Computer Vision Foundation