package:
  name: {{ RECIPE }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_rev: {{ GIT_DESCRIBE_TAG }}
  git_url: https://github.com/open-mmlab/mmdetection.git

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - cudatoolkit-dev=10.1
    - pip
    - python=3.7
    - pytorch=1.5
  run:
    - cudatoolkit-dev=10.1
    - matplotlib
    - mmcv
    - pillow=7
    - pytorch=1.5
    - six
    - terminaltables
    - torchvision
test:
  imports:
    - mmdet

about:
  home: https://mmdetection.readthedocs.io/en/latest/
  license: Apache License
  license_family: APACHE
  summary: Composable command line interface toolkit
