package:
  name: {{ environ.get('RECIPE', 'mmdetection') | lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_rev: {{ GIT_DESCRIBE_TAG }}
  git_rev: v2.3.0
  git_url: https://github.com/open-mmlab/mmdetection.git

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  features:
{{ environ.get('CONDA_CPUONLY_FEATURE') }}
  script_env:
    - CONDA_CPUONLY_FEATURE

requirements:
  host:
    - cython
    - pip
    - python=3.7
    - pytorch=1.6
  run:
#    - addict          # mmcv
    - matplotlib
    - mmcv>=1.0.5
    - opencv
    - pycocotools
    - python=3.7
#    - pytorch=1.6
#    - pyyaml          # mmcv
#    - regex           # [win] # mmcv
    - six
    - terminaltables
#    - torchvision
#    - yapf            # mmcv
{{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}
test:
  imports:
    - mmdet

about:
  home: https://github.com/open-mmlab/mmdetection
  license: Apache License 2.0
  license_family: APACHE
  summary: OpenMMLab Detection Toolbox and Benchmark