{% set version = "0.5.21" %}

package:
  name: ml-ws
  version: {{ version }}

source:
  git_rev: v{{ version }}
  git_url: https://gitlab.com/necla-ml/ML-WS.git

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

requirements:
  build:
#    - gcc_linux-64  # [linux]
#    - gxx_linux-64  # [linux]
    - pkg-config
    - automake
    - cmake
  host:
    - cffi
    - cmake
    - git
    - libcurl
    - ml>=0.11.1      # ml.shutils
    - openssl
    - pip
    - python=3.6
    - setuptools
  run:
    - cffi
    - cmake
    - ml>=0.11.0
    - python=3.6
    - youtube-dl
    - stomp.py
test:
  imports:
    - ml.iot
    - ml.streaming
    - ml.ws.broker
  commands:
    - $PYTHON -c 'import torch; import ml.streaming._C'

about:
  home: https://gitlab.com/necla-ml/ML-WS
  license: BSD
  license_family: BSD
  summary: IoT and Streaming subpackages of ML