{% set version = "4.4.1" %} # semver: (x.y.z)
{% set x,y,z = version.split('.') %}
{% set version_ffmpeg_style = x ~ '.' ~ y if z == "0" else version %}

package:
  name: ffmpeg
  version: {{ version }}

source:
  url: https://ffmpeg.org/releases/ffmpeg-{{ version_ffmpeg_style }}.tar.gz
  # sha256: 2f5b24f30e41963ce80f0ab7c78a1b91e86fb3fbb4a7661147c572c587177eee
  patches:
  {% if license_family == 'ntp_rtp_patch' %}
    - patches/add_rtp_ntp_timestamp_4.4.1.patch
  {% endif %}

{% set number = 0 %}
{% if license_family == 'gpl' %}
    {% set number = number + 100 %}
{% endif %}

build:
  number: {{ number }}
  string: {{ license_family }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  run_exports:
  # seems to be major version compatibility
  # https://abi-laboratory.pro/tracker/timeline/ffmpeg/
    - {{ pin_subpackage('ffmpeg', max_pin='x') }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - pkg-config  # [not win]
    - libtool  # [not win]
    - nasm  # [not win]
    - lame  # [not win]
    - make  # [not win]
  host:
    - bzip2
    - libpng
    - freetype
    - gnutls  # [not win]
    - libiconv
    - zlib
    {% if license_family == 'gpl' %}
    - x265
    - x264
    {% endif %}
    - openh264  # [not win]
    - lame  # [not win]
    - gmp  # [unix]
    - nettle # [not win]
  run:
    - bzip2
    - libpng
    - freetype
    - gnutls  # [not win]
    - libiconv
    - zlib
    {% if license_family == 'gpl' %}
    - x265
    - x264
    {% endif %}
    - openh264  # [not win]
    - lame  # [not win]
    - gmp  # [unix]
    - nettle  # [not win]

{% set grep = "grep" %}  # [unix]
{% set grep = "findstr" %}  # [win]

test:
  commands:
    - ffmpeg --help
    - ffmpeg -loglevel panic -protocols | grep "https"  # [not win]
    - ffmpeg -loglevel panic -codecs | grep "libmp3lame"  # [not win]
    - ffmpeg -loglevel panic -codecs | grep "DEVI.S zlib"  # [unix]
    - ffmpeg -loglevel panic -codecs | grep "DEV.LS h264"  # [unix]
    - ffmpeg -loglevel panic -codecs | grep "libopenh264"  # [unix]
    # Verify dynamic libraries on all systems
    {% set ffmpeg_libs = [
        "avdevice",
        "swresample",
        "avfilter",
        "avcodec",
        "avformat",
        "swscale",
        "avutil",
    ] %}
    {% for each_ffmpeg_lib in ffmpeg_libs %}
    - test -f $PREFIX/lib/lib{{ each_ffmpeg_lib }}${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\lib\\{{ each_ffmpeg_lib }}.lib exit 1  # [win]
    {% endfor %}


about:
  home: https://www.ffmpeg.org/
  license: GPL-2.0-or-later  # [license_family=='gpl']
  license: LGPL-2.1-or-later  # [license_family=='lgpl']
  license_file:
    - COPYING.GPLv2            # [license_family=='gpl']
    - COPYING.GPLv3            # [license_family=='gpl']
    - COPYING.LGPLv2.1         # [license_family=='lgpl']
    - COPYING.LGPLv3           # [license_family=='lgpl']
  license_family: GPL  # [license_family=='gpl']
  license_family: LGPL  # [license_family=='lgpl']
  summary: Cross-platform solution to record, convert and stream audio and video.
  dev_url: https://git.ffmpeg.org/ffmpeg.git
  doc_url: https://ffmpeg.org/documentation.html

extra:
  recipe-maintainers:
    - deepsworld