package:
  name: {{ RECIPE | lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_rev: {{ GIT_DESCRIBE_TAG }}
  git_rev: v0.8.5
  git_url: https://gitlab.com/necla-ml/ML.git

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  script: pip install -vv --no-deps --ignore-installed --no-build-isolation --no-binary ':all:' .
  features:
{{ environ.get('CONDA_CPUONLY_FEATURE', '') }}

requirements:
  build:
#    - gcc_linux-64  # [linux]
#    - gxx_linux-64  # [linux]
  host:
    - numexpr
    - pip
    - python=3.7
    - pytorch=1.6
    - setuptools
{{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT', '') }}
  run:
    - accimage>=0.1.1           # [not osx]
    - anaconda-client
    - av>=8.0.1
    - blosc-hdf5-plugin
    - boto3
    - conda-build
    - cython=0.29
    - git
    - git-lfs
    - h5py>=2.10
    - ignite
    - line_profiler>=2.1.2
    - matplotlib>=3.1.1
    - numba                     # optional: experimental speedup with JIT
    - numexpr
    - numpy=1.17                # https://github.com/cocodataset/cocoapi/issues/356
    - pandas>=0.25.1
    - lbzip2
    - opencv
    - pigz
    - pillow
    - pip
    - psutil                    # number of physical cores
    - pygments>=2.4.2
    - pytables>=3.5.2
    - pytest>=5.2.0
    - python=3.7
    - python-daemon
    - pytorch=1.6
    - pyyaml>=5.1.2
    - requests-toolbelt         # multipart streaming over HTTP
    - setuptools>=41.2
    - six>=1.12
    - scikit-learn>=0.21.3      # required by BERT
    - tensorboard>=2.1
    - transformers>=2.1.1
{{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT', '') }}
{{ environ.get('MAGMA_PACKAGE', '') }}
test:
  requires:
    - pytest
  imports:
    - ml.av
    - ml.cv
  source_files:
    - setup.cfg
    - tests
  commands:
#    - $PYTHON -c 'import torch; import ml._C'
    - pytest tests -m essential

about:
  home: https://gitlab.com/necla-ml/ML
  license: BSD
  license_family: BSD
  summary: NECLA Machine Learning Framework