package:
  name: {{ environ.get('RECIPE', 'ml') | lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_rev: {{ GIT_DESCRIBE_TAG }}
  git_rev: v1.4.0
  git_url: https://github.com/necla-ml/ML.git

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  script: pip install -vv --no-deps --ignore-installed --no-build-isolation --no-binary ':all:' .
  features:
{{ environ.get('CONDA_CPUONLY_FEATURE', '') }}

requirements:
  build:
#    - gcc_linux-64  # [linux]
#    - gxx_linux-64  # [linux]
  host:
    - pip
    - python={{ PY_VER }}
    - pytorch={{ PTH_VER }}
    - setuptools
{{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT', '') }}
  run:
    - anaconda-client
    - blosc-hdf5-plugin
    - boa
    - boto3
    - conda-build
    - cython
    - flake8
    - git
    - git-lfs
    - h5py>=2.10
    - ignite
    - line_profiler>=2.1.2
    - matplotlib>=3.3.1         # figure close leak in 3.3.0
    - mamba                     # drop-in conda replacement in C/C++
    - numba>=0.52               # optional: experimental speedup with JIT
    - numexpr
#    - numpy
    - pandas>=0.25.1
    - lbzip2
    - pigz
    - pip
    - psutil                    # number of physical cores
    - pygments>=2.4.2
    - pytables>=3.5.2
    - pytest>=5.2.0
    - pytest-benchmark
    - python={{ PY_VER }}
    - python-daemon
    - pytorch={{ PTH_VER }}
    - pyyaml>=5.1.2
    - requests-toolbelt         # multipart streaming over HTTP
    - setuptools>=41.2
    - six>=1.12
    - scikit-learn>=0.21.3      # required by BERT
    - tensorboard>=2.1
#    - torchvision=0.10.0
    - transformers>=2.1.1
{{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT', '') }}
{{ environ.get('MAGMA_PACKAGE', '') }}
test:
  requires:
    - pytest
  imports:
    - ml.av
#    - ml.cv
  source_files:
    - setup.cfg
    - tests
  commands:
    - pytest tests -m essential

about:
  home: https://gitlab.com/necla-ml/ML
  license: BSD
  license_family: BSD
  summary: NECLA Machine Learning Framework