package:
  name: {{ environ.get('RECIPE', 'ml-ws') | lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_rev: v0.7.0
  git_url: https://github.com/necla-ml/ML-WS.git

build:
  number: 0
  script_env:
    - PY_VER
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('PKG_BUILDNUM') }}

requirements:
  build:
#    - gcc_linux-64  # [linux]
  host:
    - cffi
    - necla-ml::kvs-producer-sdk
    - necla-ml::ml>=1.4.9         # ml.shutils
    - pip
    - python={{ PY_VER }}
    - setuptools
  run:
    - cffi
    - necla-ml::kvs-producer-sdk
    - necla-ml::ml>=1.4.9
    - python={{ PY_VER }}
    - gstreamer=1.21.3
    - gst-plugins-good
    - gst-plugins-bad
    - gst-plugins-ugly
    - necla-ml::gst-libav=1.21.3  # compiled with ffmpeg=4.4.2
    - gst-python
    - youtube-dl
    - awscli
test:
  imports:
    - ml.iot
    - ml.streaming
    - ml.ws
  commands:
    - $PYTHON -c 'import torch; import ml.streaming._C'

about:
  home: https://github.com/necla-ml/ML-WS
  license: BSD
  license_family: BSD
  summary: IoT and Streaming subpackages of ML