package:
  name: {{ environ.get('RECIPE', 'ml-ws') | lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_rev: {{ GIT_DESCRIBE_TAG }}
  git_rev: v0.5.32
  git_url: https://github.com/necla-ml/ML-WS.git

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ GIT_BUILD_STR }}{% endif %}

requirements:
  build:
#    - gcc_linux-64  # [linux]
  host:
    - cffi
    - kvs-producer-sdk
    - ml>=1.4.5         # ml.shutils
    - pip
    - python={{ PY_VER }}
    - setuptools
  run:
    - cffi
    - kvs-producer-sdk
    - ml>=1.4.5
    - python={{ PY_VER }}
    - youtube-dl
    - stomp.py
test:
  imports:
    - ml.iot
    - ml.streaming
    - ml.ws
  commands:
    - $PYTHON -c 'import torch; import ml.streaming._C'

about:
  home: https://gitlab.com/necla-ml/ML-WS
  license: BSD
  license_family: BSD
  summary: IoT and Streaming subpackages of ML