package:
  name: {{ environ.get('RECIPE', 'ml-ws') | lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_rev: {{ GIT_DESCRIBE_TAG }}
  git_rev: v0.5.34
  git_url: https://github.com/necla-ml/ML-WS.git

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  number: 0
  script_env:
    - PY_VER
    - PTH_VER
    - PTV_VER
    - CUDA_PT_VER
    - TORCH_CUDA_ARCH_LIST
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('PKG_BUILDNUM') }}

requirements:
  build:
#    - gcc_linux-64  # [linux]
  host:
    - cffi
    - kvs-producer-sdk
    - ml>=1.4.5         # ml.shutils
    - pip
    - python={{ PY_VER }}
    - setuptools
  run:
    - cffi
    - kvs-producer-sdk
    - ml>=1.4.5
    - python={{ PY_VER }}
    - gstreamer>=1.18.5
    - gst-plugins-good
    - gst-plugins-bad
    - gst-plugins-ugly
    - gst-libav
    - gst-python
    - youtube-dl
    - awscli
test:
  imports:
    - ml.iot
    - ml.streaming
    - ml.ws
  commands:
    - $PYTHON -c 'import torch; import ml.streaming._C'

about:
  home: https://github.com/necla-ml/ML-WS
  license: BSD
  license_family: BSD
  summary: IoT and Streaming subpackages of ML