package:
  name: {{ environ.get('RECIPE', 'ml-vision') | lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_rev: {{ GIT_DESCRIBE_TAG }}
  git_rev: v0.15.3
  git_url: https://github.com/necla-ml/ML-Vision.git

build:
  # GIT_BUILD_STR={GIT_DESCRIBE_NUMBER}_{GIT_DESCRIBE_HASH}
  number: {{ GIT_DESCRIBE_NUMBER }}
  number: 0
  script_env:
    - PY_VER
    - PTH_VER
    - PTV_VER
    - CUDA_PT_VER
    - TORCH_CUDA_ARCH_LIST
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_{{ environ.get('GIT_DESCRIBE_NUMBER', '0') }}
  string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_{{ environ.get('PKG_BUILDNUM') }}
  script: pip install -vv --no-deps --ignore-installed --no-build-isolation --no-binary ':all:' .
  features:
{{ environ.get('CONDA_CPUONLY_FEATURE', '') }}

requirements:
  build:
#    - gcc_linux-64  # [linux]
#    - gxx_linux-64  # [linux]
#    - compilers  # [linux]
#    - cxx-compiler
# {{ environ.get('CONDA_NVCC_CONSTRAINT', '') }}
  host:
    - ml>=1.4.7
{{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT', '') }}
  run:
    - accimage>=0.1.1           # [not osx]
    - necla-ml::av>=9.1.0
    - necla-ml::timm>=0.6.7  
    - ml>=1.4.7
    - opencv                    # requires `jpeg>=9d` from conda-forge
    - scikit-learn              # required by ml.plot for confusion_matrix
    - pytorch::torchvision={{ PTV_VER }} # in case of unexpected downgrade
    - necla-ml::ffmpeg>=4.4.1   # force LGPL-ED ffmpeg from NECLA-ML channel
    - pycocotools>=2.0.2
    - seaborn                   # required by yolov5-v4.0
{{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT', '') }}
{{ environ.get('MAGMA_PACKAGE', '') }}
test:
  requires:
    - pytest
  #  - opencv-python             # required by YOLOv5
  imports:
    - ml.av
  source_files:
    - setup.cfg
    - tests
    - assets
  commands:
    - $PYTHON -c 'import torch; import ml._C'
    - pytest -m essential

about:
  home: https://github.com/necla-ml/ML-Vision
  license: BSD
  license_family: BSD
  summary: User facing ML vision library
