package:
  name: {{ RECIPE | lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_rev: {{ GIT_DESCRIBE_TAG }}
  git_rev: v0.6.0
  git_url: https://gitlab.com/necla-ml/ML-Vision.git

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  features:
{{ environ.get('CONDA_CPUONLY_FEATURE', '') }}
  script: pip install -vv --no-deps --ignore-installed --no-build-isolation --no-binary ':all:' .

requirements:
  build:
#    - gcc_linux-64  # [linux]
#    - gxx_linux-64  # [linux]
  host:
    - ml>=0.8.5
{{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT', '') }}
  run:
    - ml>=0.8.5
    - pycocotools>=2
    - torchvision
{{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT', '') }}
{{ environ.get('MAGMA_PACKAGE', '') }}
test:
  requires:
    - pytest
  imports:
    - ml.av
    - ml.cv
    - ml.vision.ops
  source_files:
    - setup.cfg
    - tests
    - assets
  commands:
    - $PYTHON -c 'import torch; import ml._C'
    - pytest -m essential

about:
  home: https://gitlab.com/necla-ml/ML-Vision
  license: BSD
  license_family: BSD
  summary: Composable command line interface toolkit