package:
  name: {{ environ.get('RECIPE', 'ml-vision') | lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_rev: v0.20.0
  git_url: https://github.com/necla-ml/ML-Vision.git

build:
  # GIT_BUILD_STR={GIT_DESCRIBE_NUMBER}_{GIT_DESCRIBE_HASH}
  number: {{ GIT_DESCRIBE_NUMBER }}
  number: 0
  script_env:
    - PY_VER
    - PTH_VER
    - PTV_VER
    - CUDA_PT_VER
    - TORCH_CUDA_ARCH_LIST
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('BLD_STR_SUFFIX') }}_{{ environ.get('PKG_BUILDNUM') }}
  script: pip install -vv --no-deps --ignore-installed --no-build-isolation --no-binary ':all:' .
  features:
{{ environ.get('CONDA_CPUONLY_FEATURE', '') }}

requirements:
  build:
  host:
    - ml>=1.4.9
  run:
    - accimage>=0.1.1                     # [not osx]
    - conda-forge::av=9.2.0
    - necla-ml::ml>=1.4.9
    # - conda-forge::opencv=4.5             # requires `jpeg>=9d` from conda-forge
    - necla-ml::opencv-python
    - scikit-learn                        # required by ml.plot for confusion_matrix
    - pytorch::torchvision={{ PTV_VER }}  # in case of unexpected downgrade
    - conda-forge::ffmpeg>=4.4.2=*lgpl*    # force LGPL-ED ffmpeg
    - pycocotools>=2.0.2
    - conda-forge::sdl2
    - conda-forge::loguru
    - conda-forge::tabulate
    - conda-forge::timm
test:
  requires:
    - pytest
  imports:
    - ml.av
  source_files:
    - setup.cfg
    - tests
    - assets
  commands:
    - pytest -m essential

about:
  home: https://github.com/necla-ml/ML-Vision
  license: BSD
  license_family: BSD
  summary: User facing ML vision library
